In [1]:
%load_ext autoreload
%autoreload 2

from utils import Snake
import random

In [2]:
# to do
write q_learning bot

SyntaxError: invalid syntax (<ipython-input-2-0cfa672a3176>, line 2)

### player mode

In [3]:
from utils import Snake
sizes = (8, 6)
sn = Snake(sizes)
sn.play()

<generator object Snake.play at 0x000001F20EE87E60>

In [65]:
sn.reset()

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 2, 2, 3, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

### Stupid Bot

In [3]:
class StupidBot():
    def __init__(self):
        pass
    def compute(snake = None, grille = None):
        rand = random.randint(1, 4)
        rand_to_input = {
                    1 : 6, #right
                    2 : 4,
                    3 : 8,
                    4 : 5

                }
        return rand_to_input[rand]

In [6]:
sbot = StupidBot()

In [121]:
from utils import Snake
sizes = (8, 6)
sn = Snake(sizes, sbot)

In [122]:
score = sn.play()

Score : 0
[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 4, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 2, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 2, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 3, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
last_direction down
impossible
direction down
user_input continue
None
crash: Final Score is 0


### Simulate average score for 1000 games of stupid bot

In [30]:
histories = []
scores = []
for i in range(1000):
    sizes = (8, 6)
    sn = Snake(sizes, sbot)
    score, history = sn.play()
    scores.append(score)
    histories.append(history)

Score : 0
[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 3, 2, 2, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 4, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
last_direction left
impossible
direction left
user_input continue
None
crash: Final Score is 0


fix error for one thousand 

In [31]:
import numpy as np
np.mean(scores)

1.66

In [15]:
[i for i,s in enumerate(scores) if s =="score"]

[392, 539, 585, 943]

In [18]:
histories[585]

{'grille': [[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 2, 2, 3, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 4, 0, 0, 0, 0, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
  [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 2, 2, 3, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 4, 0, 0, 0, 0, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
  [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 2, 2, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 3, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 4, 0, 0, 0, 0, 1],
   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
  [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
   [1, 0, 0, 0, 2, 0, 0, 0, 0, 1],
   [1, 

In [11]:
sbot = StupidBot()
sizes = (8, 6)
sn = Snake(sizes, sbot)

In [12]:
sn.play()

Score : 0
[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 2, 0, 0, 0, 0, 1],
 [1, 4, 0, 0, 2, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 3, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
last_direction down
impossible
direction down
user_input continue
None
crash: Final Score is 0


(0,
 {'grille': [[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 2, 2, 3, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 4, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
   [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 2, 2, 3, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 4, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
   [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 2, 2, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 3, 0, 0, 0, 0, 1],
    [1, 4, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
   [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 

In [174]:
a = [1,2,3]
b = copy(a)
a.append(1)

In [181]:
b

[1, 2, 3]

In [169]:
copy(a)

Le fichier sp‚cifi‚ est introuvable.


In [170]:
from copy import copy

In [36]:
a = histories[2]["grille"][0]

In [43]:
from sklearn.preprocessing import scale
import pprint
pprint.pprint(scale(np.matrix(a)))

array([[ 0.        ,  0.70710678,  0.70710678,  0.37796447,  1.73205081,
         1.73205081,  1.73205081,  0.19245009,  1.73205081,  0.        ],
       [ 0.        , -0.70710678, -0.70710678, -0.62994079, -0.57735027,
        -0.57735027, -0.57735027,  2.50185117, -0.57735027,  0.        ],
       [ 0.        , -0.70710678, -0.70710678, -0.62994079, -0.57735027,
        -0.57735027, -0.57735027, -0.57735027, -0.57735027,  0.        ],
       [ 0.        ,  2.12132034,  2.12132034,  2.393775  , -0.57735027,
        -0.57735027, -0.57735027, -0.57735027, -0.57735027,  0.        ],
       [ 0.        , -0.70710678, -0.70710678, -0.62994079, -0.57735027,
        -0.57735027, -0.57735027, -0.57735027, -0.57735027,  0.        ],
       [ 0.        , -0.70710678, -0.70710678, -0.62994079, -0.57735027,
        -0.57735027, -0.57735027, -0.57735027, -0.57735027,  0.        ],
       [ 0.        , -0.70710678, -0.70710678, -0.62994079, -0.57735027,
        -0.57735027, -0.57735027, -0.57735027

C:\Users\arman\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [45]:
b = histories[2]["grille"][1]

In [48]:
np.matrix(b) - np.matrix(a)

matrix([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, -2,  0, -1,  3,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [49]:
# Karpathy code
# https://gist.github.com/karpathy/a4166c7fe253700972fcbc77e4ea32c5


[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 4, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 2, 2, 3, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

In [54]:
a = np.array(a)
scale(a.reshape(-1, 1))

In [57]:
scale(a.reshape(-1, 1))

C:\Users\arman\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.63916724],
       [ 0.63916724],
       [ 0.63916724],
       [ 0.63916724],
       [ 0.63916724],
       [ 0.63916724],
       [ 0.63916724],
       [ 0.63916724],
       [ 0.63916724],
       [ 0.63916724],
       [ 0.63916724],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [ 4.78511693],
       [-0.74281599],
       [ 0.63916724],
       [ 0.63916724],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [ 0.63916724],
       [ 0.63916724],
       [ 2.02115047],
       [ 2.02115047],
       [ 3.4031337 ],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [ 0.63916724],
       [ 0.63916724],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0.74281599],
       [-0