In [38]:
%load_ext autoreload
%autoreload 2
%config Completer.use_jedi = False
from utils import Snake
import random
import pickle
import numpy as np


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### to do
- write q_learning bot"
- /!\ dérivé du sigmoid != dérivée du softmax
- problem with bot input at each step

- write function to run the freezed model.

### player mode

### Stupid Bot

In [39]:
class StupidBot():
    def __init__(self):
        pass
    def compute(snake = None, grille = None):
        rand = random.randint(1, 4)
        rand_to_input = {
                    1 : 6, #right
                    2 : 4,
                    3 : 8,
                    4 : 5

                }
        return rand_to_input[rand]

In [40]:
sbot = StupidBot()

In [41]:
%%time
# get training data:
histories = []
scores = []
for i in range(100):
    sizes = (18, 26)
    sn = Snake(sizes, sbot)
    game_history = list(sn.play())
    histories.append(game_history)

CPU times: user 2.72 s, sys: 113 ms, total: 2.84 s
Wall time: 2.79 s


In [33]:
grille = histories[0][0][1]

In [37]:
np.mean([len(h) for h in histories])

39.66

In [34]:
grille

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 2, 2, 3, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

## at each step return:
- environment
- score
- done: if game is finished

In [21]:
import numpy as np
from sklearn.preprocessing import scale

def preprocess_grille(grille):
    
    grille = np.array(grille)
    return grille.ravel().astype(np.float)

In [28]:
preprocess_grille(grille=grille)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 9., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 2., 2., 3.,
       0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
model = pickle.load(open('save.3p', 'rb'))
model

{'W1': array([[-0.21505932,  0.06670894, -0.12467508, ...,  0.02435351,
          0.00279704,  0.07124356],
        [ 0.10453152, -0.0862175 , -0.10753936, ..., -0.00523612,
          0.06266721, -0.07110381],
        [ 0.12498902,  0.02536624,  0.01488435, ..., -0.00111495,
         -0.01106443, -0.32190237],
        ...,
        [ 0.01401738,  0.01279135,  0.03750998, ..., -0.10592342,
         -0.15228036,  0.14095975],
        [ 0.15244357, -0.03653131,  0.1387653 , ..., -0.20959031,
         -0.39766411, -0.04523126],
        [-0.12300799,  0.01715861, -0.1091387 , ...,  0.12858187,
          0.07883236,  0.0438715 ]]),
 'W2': array([[ 1.00448254e-01,  1.74054956e-02,  1.13168065e-02,
          1.33127979e-01],
        [ 1.05251989e-01,  5.23163955e-02,  1.48608487e-02,
          1.57001456e-02],
        [-7.73507213e-02, -1.93916255e-01,  7.22462955e-02,
         -5.33170308e-03],
        [ 1.61916071e-02,  9.15177635e-02,  1.08364331e-01,
         -2.31669280e-02],
        [-1.5

In [29]:
position_to_input = {
    0: 4,
    1: 5,
    2: 3,
    3: 8
}
A = 4
H = 200 # number of hidden layer neurons
batch_size = 10 # every how many episodes to do a param update?
learning_rate = 1e-4
gamma = 0.99 # discount factor for reward
decay_rate = 0.99 # decay factor for RMSProp leaky sum of grad^2
resume = True # resume from previous checkpoint?
render = False

# model initialization
D = 10 * 8 # input dimensionality: 80x80 grid
if resume:
    model = pickle.load(open('save.3p', 'rb'))
else:
    model = {}
    model['W1'] = np.random.randn(D, H) / np.sqrt(D) # "Xavier" initialization
    model['W2'] = np.random.randn(H, A) / np.sqrt(H)
    
grad_buffer = { k : np.zeros_like(v) for k,v in model.items() } # update buffers that add up gradients over a batch
rmsprop_cache = { k : np.zeros_like(v) for k,v in model.items() } # rmsprop memory

def sigmoid(x): 
    return 1.0 / (1.0 + np.exp(-x)) # sigmoid "squashing" function to interval [0,1]

def softmax(x):
    if(len(x.shape)==1):
        x = x[np.newaxis,...]
    probs = np.exp(x - np.max(x, axis=1, keepdims=True))
    probs /= np.sum(probs, axis=1, keepdims=True)
    return probs

def discount_rewards(r):
    """ take 1D float array of rewards and compute discounted reward """
    discounted_r = np.zeros_like(r)
    running_add = 0
    for t in reversed(range(0, len(r))):
        if r[t] != 0: running_add = 0 # reset score when new stuff eaten
        running_add = running_add * gamma + r[t]
        discounted_r[t] = running_add
    return np.array(discounted_r).astype(np.float)

def preprocess_grille(grille):
    
    grille = np.array(grille)
    return scale(grille.ravel().astype(np.float))

def policy_forward(x):
    if(len(x.shape)==1):
        x = x[np.newaxis,...]
    h = x.dot(model['W1'])
    h[h<0] = 0 # ReLU nonlinearity
    logp = h.dot(model['W2'])
    p = softmax(logp)
    return p, h
    
    
def policy_backward(eph, epdlogp):
    """ backward pass. (eph is array of intermediate hidden states) """
    dW2 = eph.T.dot(epdlogp)  
    dh = epdlogp.dot(model['W2'].T)
    dh[eph <= 0] = 0 # backpro prelu
  

    dW1 = epx.T.dot(dh) 
    
    return {'W1':dW1, 'W2':dW2}

In [ ]:
class SmartBot():
    def __init__(self):
        pass
    
    def compute(self):
        return self.action
    

from utils import Snake
sizes = (8, 6)
sb = SmartBot()
sn = Snake(sizes, sb)
game = sn.play()


#End BOt
#################################"


xs,hs,dlogps,drs = [],[],[],[]
running_reward = None
reward_sum = 0
episode_number = 0
last_score = 0
grille = sn.reset()

while True:
    from time import sleep
    sleep(0.8)
    from pprint import pprint
    x = preprocess_grille(grille)
    probs, h = policy_forward(x)
    u = np.random.uniform()
    aprob_cum = np.cumsum(probs)
    pprint(grille)
    a = np.where(u <= aprob_cum)[0][0]
    action = a 
    user_input = position_to_input[action]
    #print(probs)
    xs.append(x) # observation
    hs.append(h) # hidden state
    
    y = action
    sb.action = user_input
    dlogsoftmax = probs.copy()
    dlogsoftmax[0, a] -= 1 #-discounted reward 

    dlogps.append(dlogsoftmax) 
    score, grille, done = next(game)
    reward = score - last_score
    reward_sum += reward
    drs.append(reward)
    if done == "yes": # an episode finished
        episode_number += 1
        
        epx = np.vstack(xs)
        eph = np.vstack(hs)
        epdlogp = np.vstack(dlogps)
        epr = np.vstack(drs)
        xs,hs,dlogps,drs = [],[],[],[] # reset array memory

        discounted_epr = discount_rewards(epr)
        discounted_epr -= np.mean(discounted_epr)
        #discounted_epr /= np.std(discounted_epr)
        epdlogp *= discounted_epr
        grad = policy_backward(eph, epdlogp)
        for k in model: grad_buffer[k] += grad[k]

        if episode_number % batch_size == 0:
            for k,v in model.items():
                g = grad_buffer[k] # gradient
                rmsprop_cache[k] = decay_rate * rmsprop_cache[k] + (1 - decay_rate) * g**2
                model[k] += learning_rate * g / (np.sqrt(rmsprop_cache[k]) + 1e-5)
                grad_buffer[k] = np.zeros_like(v) # reset batch gradient buffer

        running_reward = reward_sum if running_reward is None else running_reward * 0.99 + reward_sum * 0.01
        print ('resetting env. episode reward total was %f. running mean: %f' % (reward_sum, running_reward))
        if episode_number % 100 == 0: pickle.dump(model, open('save.p', 'wb'))
        reward_sum = 0
        sizes = (8, 6)
        sb = SmartBot()
        sn = Snake(sizes, sb)
        game = sn.play()
        grille = sn.reset()

        if reward > 0 : # Pong has either +1 or -1 reward exactly when game ends.
            print ('ep %d: game finished, reward: %f' % (episode_number, reward))

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 2, 2, 3, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 4, 0, 0, 0, 0, 1],
 [1, 2, 2, 3, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 4, 0, 0, 0, 0, 1],
 [1, 0, 2, 2, 3, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 4, 0, 0, 0, 0, 1],
 [1, 0, 0, 2, 2, 3, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0,

In [116]:
# running reward should be much better than > 2

(6, 200)

In [60]:
probs = softmax([9, 4, 6, 9])
np.argmax(probs)

0

In [239]:
discount_rewards([1,2,5,6])

array([1, 2, 5, 6])

In [253]:
(2, None) + ('fezfz')

TypeError: can only concatenate tuple (not "str") to tuple

In [111]:
a

2

In [64]:
np.random.uniform()

0.07509607252804984

In [57]:

def get_i():
    i = 0
    while True:
        if i > 5:
            break
        i+=1
        yield i

In [58]:
for j in get_i():
    print(j)

1
2
3
4
5
6


In [109]:
a

0

In [148]:
sb.action = 

'up'

In [213]:
import time

In [9]:

from utils import Snake
sizes = (8, 6)
sn = Snake(sizes, sb)


game = sn.play()
sb = SmartBot()

for i in range(10):
    sb.action = 6
    a = next(game)
    if a[1] =="crash":
        break
    time.sleep(0.8)

AttributeError: 'Snake' object has no attribute 'initial_grille'

In [77]:
np.dot(model["W1"], h)

ValueError: shapes (200,80) and (200,) not aligned: 80 (dim 1) != 200 (dim 0)

In [76]:
model["W1"].shape


(200, 80)

In [38]:
sn.reset()

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 2, 2, 3, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

In [52]:
game = sn.play()
sb.action = 6

In [54]:
sb.action = 4
next(game)

problem with directions


UnboundLocalError: local variable 'direction' referenced before assignment

In [230]:
np.array(grille).ravel()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 3, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [91]:
np.dot(np.random.randn(200,4), np.random.randn(4))

array([ 1.03189308e+00, -2.52640944e+00, -2.74654936e+00, -2.71863245e+00,
       -1.55951285e+00, -1.79988946e+00,  1.30339179e+00, -2.47595151e+00,
        2.64795708e+00, -1.24593751e-01,  1.13366512e+00,  6.39985175e-01,
       -1.79841695e+00, -3.04610883e+00, -6.80702877e-01, -7.14400589e-01,
       -1.39055581e+00,  1.22258742e-01, -2.57020463e-01,  1.94171512e+00,
       -4.17501060e+00,  1.16446487e+00,  1.07930984e+00, -1.72321844e+00,
       -5.67678703e-01,  2.76235051e-01,  3.44678209e-01, -2.25744172e+00,
       -4.64243952e-02, -4.78627461e-01, -1.66130187e+00, -6.21698860e-01,
       -3.33046324e+00, -6.89212196e-01,  3.28116313e+00,  2.45100086e-01,
        2.26053963e+00,  1.58200224e+00,  5.38090435e-01, -2.69223043e+00,
        1.50946944e+00, -7.27487929e-01,  4.73304308e-01,  1.24560226e+00,
       -1.11032164e+00,  2.07192283e+00, -1.90999937e+00,  2.10168190e+00,
        2.97259674e-01, -8.34910787e-02, -1.18160241e+00,  2.27637875e+00,
       -3.07326782e+00, -

In [104]:
np.where(u <= aprob_cum)[0][0]

3

In [131]:
x = x[np.newaxis,...]
x

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 2.,
         2., 3., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [25]:
scores = [0,0,1,1,1,2,2,2,2]

In [26]:
last_score = 0
for i in scores:
    print(i - last_score)
    last_score = i 

0
0
1
0
0
1
0
0
0
